# 2 clusters each 1 Elasticsearch node, 1 Kibana instance with elasticsearch
# First
services:
  # elasticsearch
  es-node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: elasticsearch-single-node
    environment:
      - node.name=node01
      - cluster.name=lab-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g # Heap size
    volumes:
      - es-node-labs:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    mem_limit: 3g
    networks:
      - elastic-net
  # kibana
  kibana:
    depends_on:
      - es-node
    image: docker.elastic.co/kibana/kibana:8.1.3
    container_name: kibana-single-node
    environment:
      - ELASTICSEARCH_HOSTS=["http://es-node:9200"]
    ports:
      - 5602:5601
    networks:
      - elastic-net

volumes:
  es-node-labs:
    driver: local

networks:
  elastic-net:
